### ISSUE TITLE
Add conditional colouring to donut charts

### ISSUE THREAD

**Issue by raekw0n** [versyx-digital/raspberry-pi-monitor#2]
The donut charts should change colour depending on the value of the data they represent, for example using the CPU temperature:

Below 60 degrees: green
Between 61 and 80 degrees: yellow
Above 80 degrees: red

The conditions should be configurable via environment variables.

**Comment by Sbaah** [comment]
Hello, I would like to attempt this.

**Comment by raekw0n** [comment]
Hi @Sbaah, awesome! Feel free to go ahead and submit a pull request when you're ready, if you have any questions or need any help don't be afraid to ask.

Thanks for contributing!

**Comment by Sbaah** [comment]
Hey I was wondering if you could help set up the environment to run php websites locally ?
Have researched it but i keep find different way but non work for me.

**Comment by raekw0n** [comment]
Hey, no problem, what exactly do you need help with?

To run this project, you'll need to have PHP and Composer installed, then:

1. Clone this repository - `git clone git@github.com:versyx-digital/pi-monitor.git`
3. Change to the project directory - `cd pi-monior`
4. Run `composer install` to install the application dependencies
5. Run `npm install` to install the frontend dependencies

The next step will be to build the frontend assets (css, js, fonts etc.), this project uses [Gulp](https://gulpjs.com/) to compile and bundle scss and js files located in `assets/`, you can take a look at the the tasks located in `gulpfile.babel.js` to see what happens in more detail, but the main command to build everything is `gulp compile`, this will take all files defined in `config/assets.json`, compile css and js, copy fonts, optimize images etc. and output them to the `public/` folder.

After building the frontend assets, you'll need to create a local `.env` file and place it in the `config/` directory. The project comes with a `.env.example` file containing all the requried environment variables, so the easiest way to do this is to simply copy it:

`cp config/.env-example config/.env`

After creating it, you should then set `DEBUG=false` to `DEBUG=true`, this will load the test data located in `tests/` instead of trying to query the [API](https://github.com/versyx-digital/pi-monitor-api).

After you've done all of the above, the application should be ready to view. If you have PHP installed on your host machine, you can use the build in web server, from the `public/` directory, run:

`php -S localhost:8000`

If you have Apache installed, you can set up a vhost instead:

Create a new file named `pi-monitor.local.conf` in `/etc/apache2/sites-available` with the following:

```
<VirtualHost *:80>
    ServerName pi-monitor.local
    ServerAlias www.pi-monitor.local
    DocumentRoot /your/path/to/pi-monitor/public
    <Directory /your/path/to/pi-monitor/public>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride all
            Require all granted
    </Directory>
    ErrorLog /var/log/apache2/pi-monitor-error.log
    CustomLog /var/log/apache2/pi-monitor-access.log combined
</VirtualHost>
```
Then enable it with a symlink to `/etc/apache2/sites-enabled/`:

`sudo ln -s /etc/apache2/sites-available/pi-monitor.local.conf /etc/apache2/sites-enabled/`

Finally, restart apache and edit your hosts file located at `/etc/hosts` with the following:

`127.0.0.1    pi-monitor.local`

You should now be able to view the application at http://pi-monitor.local 😃

**Comment by Sbaah** [comment]
Hello am still interested is just haven't gotten around to doing it yet.
